### ISSUE TITLE
Change solium to solhint for linting 

### ISSUE THREAD

**Issue by rbval** [identity-com/smart-contracts#3]
Solium gets slower on larger contracts. [Solhint](https://protofire.github.io/solhint/) is quite light and supports all solidity style guides.

**Comment by tituscapilnean** [comment]
We used Solhint initially but at some point in time we had to switch to Solium as it was developing faster and supported latest solidity syntax earlier. Solium also has some unique features we use, e.g. custom rules via plugins. We find zeppelin's security plugins quite useful. The execution speed difference is negligible (i.e. fraction of a second) with total execution time less than 2 seconds, so we wouldn't consider this to be a concern. Both projects are in development so we might re-evaluate them in nearest future, but at this point we do not see a strong need for switching the linter.
